name: WakaTime Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours

jobs:
  update-readme:
    name: Update WakaTime Stats in README
    runs-on: ubuntu-latest

    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}              
          BLOCKS: "□■"               
          TIME_RANGE: all_time              
